# Generated by Django 6.0.5 on 2026-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('distance_unit', models.CharField(max_length=20)),
                ('fuel_volume_unit', models.CharField(max_length=20)),
                ('fuel_economy_unit', models.CharField(max_length=20)),
                ('ev_price_unit', models.CharField(default='kWh', max_length=20)),
                ('ev_efficiency_unit', models.CharField(default='km/kWh', max_length=20)),
                ('fuel_price_min', models.FloatField(default=0)),
                ('fuel_price_max', models.FloatField(default=200)),
                ('ev_price_min', models.FloatField(default=0)),
                ('ev_price_max', models.FloatField(default=50)),
                ('fuel_efficiency_min', models.FloatField(default=1)),
                ('fuel_efficiency_max', models.FloatField(default=100)),
                ('ev_efficiency_min', models.FloatField(default=2)),
                ('ev_efficiency_max', models.FloatField(default=12)),
                ('speed_min', models.FloatField(default=10)),
                ('speed_max', models.FloatField(default=200)),
                ('yearly_distance_min', models.IntegerField(default=1000)),
                ('yearly_distance_max', models.IntegerField(default=100000)),
                ('fuel_types', models.JSONField(default=list)),
                ('subscription_plans', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
