# Generated by Django 6.0.5 on 2026-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_customersupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupport',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customersupport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
