# Generated by Django 6.0.5 on 2026-07-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryconfig',
            name='ev_energy_unit',
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='ev_efficiency_max',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='ev_efficiency_min',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='ev_efficiency_unit',
            field=models.CharField(default='km/kWh', max_length=20),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='ev_price_max',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='ev_price_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='ev_price_unit',
            field=models.CharField(default='kWh', max_length=20),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='fuel_efficiency_max',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='fuel_efficiency_min',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='fuel_price_max',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='fuel_price_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='speed_max',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='speed_min',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='yearly_distance_max',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='countryconfig',
            name='yearly_distance_min',
            field=models.IntegerField(default=1000),
        ),
    ]
