# Generated by Django 6.0.6 on 2026-06-23 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerfactor',
            name='occupants',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
