# Generated by Django 6.0.5 on 2026-07-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(default='AU', max_length=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan_code',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], default='basic', max_length=30),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
