# Generated by Django 6.0.5 on 2026-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_capacity',
            field=models.FloatField(blank=True, help_text='Battery capacity in kWh (Only for EV)', null=True),
        ),
    ]
