# Generated by Django 6.0.5 on 2026-07-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_battery_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='yearly_km',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
