# Generated by Django 6.0.5 on 2026-07-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3)),
                ('phone_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('state_code', models.CharField(blank=True, max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='location.country')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('country', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='location.state')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('state', 'external_id')},
            },
        ),
    ]
