# Generated by Django 6.0.5 on 2026-07-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='city',
            name='external_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='external_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='state',
            name='external_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'external_id')},
        ),
    ]
