# Generated by Django 6.0.5 on 2026-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cycle', models.BooleanField(default=False)),
                ('trip_type', models.CharField(choices=[('car', 'Car'), ('cycle', 'Cycle'), ('other', 'Other')], default='car', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0.0)),
                ('average_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('co2_emission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_location', models.CharField(blank=True, default='', max_length=500)),
                ('destination', models.CharField(blank=True, default='', max_length=500)),
                ('country_code', models.CharField(default='IN', max_length=5)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_archieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(default=0.0)),
                ('time', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Trip Data',
                'verbose_name_plural': 'Trip Data',
                'ordering': ['time'],
            },
        ),
    ]
