# Generated by Django 6.0.5 on 2026-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripanalytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='co2_saved',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Positive = CO2 saved, Negative = Extra CO2 emitted', max_digits=10, null=True),
        ),
    ]
